App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create','edit']
    country:
      - NotBlank:
          groups: ['create','edit']
    latitude:
      - NotBlank:
          groups: ['create','edit']
      - Range:
          min: -90
          max: 90
          groups: ['create','edit']
    longitude:
      - NotBlank:
          groups: ['create','edit']
      - Range:
          min: -90
          max: 90
          groups: [ 'create','edit' ]


App\Entity\Forcast:
  properties:
    precipation_probability:
      - NotBlank:
         groups: ['create','edit']
      - Range:
         min: 0
         max: 100
         groups: ['create','edit']